public class Main {
    public static void main(String[] args) {
        System.out.println("Задача 1");
        var dog = 8.0;
        System.out.println("Значение переменной dog равно " + dog);
        var cat = 3.6;
        System.out.println("Значение переменной cat равно " + cat);
        var paper = 763789;
        System.out.println("Значение переменной paper равно " + paper);
        System.out.println("Задача 2");
        dog = dog + 4;
        System.out.println("Новое значение переменной dog равно " + dog);
        cat = cat + 4;
        System.out.println("Новое значение переменной cat равно " + cat);
        paper = paper + 4;
        System.out.println("Новое значение переменной paper равно " + paper);
        System.out.println("Задача 3");
        dog = dog - 3.5;
        System.out.println("Новое значение переменной dog равно " + dog);
        cat = cat - 1.6;
        System.out.println("Новое значение переменной cat равно " + cat);
        paper = paper - 7639;
        System.out.println("Новое значение переменной paper равно " + paper);
        System.out.println("Задача 4");
        var friend = 19;
        System.out.println("Значение переменной friend равно " + friend);
        friend = friend +  2;
        System.out.println("Новое значение переменной friend равно " + friend);
        friend = friend / 7;
        System.out.println("Новое значение переменной friend равно " + friend);
        System.out.println("Задача 5");
        var frog = 3.5;
        System.out.println("Значение переменной frog равно " + frog);
        frog = frog * 10;
        System.out.println("Новое значение переменной frog равно " + frog);
        frog = frog / 3.5;
        System.out.println("Новое значение переменной frog равно " + frog);
        frog = frog + 4;
        System.out.println("Новое значение переменной frog равно " + frog);
        System.out.println("Задача 6");
        var boxer1 = 78.2;
        var boxer2 = 82.7;
        var boxerTotal = boxer1 + boxer2;
        var boxerDiff = boxer1 - boxer2;
        System.out.println("Общая масса двух бойцов равна " + boxerTotal + " кг");
        System.out.println("Разница между массами бойцов равна " + boxerDiff + " кг");
        System.out.println("Задача 7");
        boxerDiff = boxer2 - boxer1;
        System.out.println("Разница между массами бойцов (вычитание) равна " + boxerDiff + " кг");
        boxerDiff = boxer2 % boxer1;
        System.out.println("Разница между массами бойцов (остаток) равна " + boxerDiff + " кг");
        System.out.println("Задача 8");
        var totalTime = 640;
        var workerTime = 8;
        var worker = totalTime / workerTime;
        System.out.println("Всего работников в компании - " + worker + " человек");
        worker = worker + 94;
        totalTime = worker * workerTime;
        System.out.println("Если в компании работает " + worker + " человек, то всего " + totalTime + " часов работы может быть поделено между сотрудниками");
    }
}